version: "3.7"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - ./data/pgadmin-data:/var/lib/pgadmin

#  web:
#    build: .
#    environment:
#      - TOKEN=${TOKEN}
#      - HOST=${HOST}
#      - OXYGENCS_TOKEN=${OXYGENCS_TOKEN}
#      - TICKETS=${TICKETS}
#      - T_MAX=${T_MAX}
#      - T_MIN=${T_MIN}
#    ports:
#      - "8000:5000"