name: Oxygen-CS CI pipeline
run-name: Oxygen-CS CI pipeline
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r libraries.txt  

      - name: Run app
        run: |
          python app.py

#      - name: Run unit tests
#        run: python -m unittest discover
  
