name: Oxygen-CS CI pipeline
run-name: Oxygen-CS CI pipeline
on:
  push:
    branches:
      - main

env:
#   TOKEN: ${{ secrets.TOKEN }}
#   HOST: ${{ secrets.HOST }}
#   OXYGENCS_TOKEN: ${{ secrets.OXYGENCS_TOKEN }}
#   TICKETS: ${{ secrets.TICKETS }}
#   T_MAX: ${{ secrets.T_MAX }}
#   T_MIN: ${{ secrets.T_MIN }}
  DOCKER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/log680repo
  DOCKER_IMAGE_TAG: oxygencs-1.${{ github.run_number }}

jobs:
  setup_and_qa:
    name: Setup Python, run unit tests and hooks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r libraries.txt  
          pip install pre-commit
          pre-commit install
          
      - name: Run unit tests
        run: |
          python -m unittest discover -s unit_testing/app

      - name: Run Pre-commit hook
        run: |
          pre-commit run

  docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: setup_and_qa
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/log680repo
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
      
      - name: Build Docker image and upload the image to DockerHub
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{env.DOCKER_IMAGE_NAME}}:${{ env.DOCKER_IMAGE_TAG }}, ${{ steps.meta.outputs.tags }}
  
