name: Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Run unit tests
        run: pytest test/test.py
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Replace 'x' with the desired Python version  
      - name: Run unit tests
        run: pytest
